version: '3'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: assistant
      POSTGRES_PASSWORD: assistantpass
      POSTGRES_DB: assistant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_DATABASE: assistant_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: